### PR TITLE
Ft home page 160277500

### PR DESCRIPTION
**Pull request by sekayasin**
## 3Fs Landing Page 
This commit delivers a landing page for Fast-Food-Fast website
checkout the landing page hosted on github pages [here](https://sekayasin.github.io/3Fs/UI)

### Slow internet connection, page loading my delay, this is why..
- Lato Google Font has been used for typograpghy.
- Images and backgrounds images are embedded from unsplash.  website first fetchs them..

### CODE REVIEW

**Comment by Nta1e** [comment]
wow..**Impressing**

**Comment by sekayasin** [comment]
@NtaleShadik giving it a realHard try bro! Yap! wen doing Frontend sh!t No frontend frameworks attached!, You just feel like u want to die and end the pain..!

**Comment by Nta1e** [comment]
Isn't it worth it though? I mean...

**Comment by sekayasin** [comment]
Yesss! its worth it.. coz u get to feel more power and control of your css u've written.. tho in the modern frontend tooling, Speed and Accuracy is Key! wen yo authoring yo own css, speed aint on yo side bro.. and u sit the all day trying to mek your header image load a coloured image on hover..., wen it works u feel the power! its pretty awesome!

**Comment by SokoPaulSokool** [comment]
Great work. It is also a good idea to put more effort into finishing the required features for the challenge

**Comment by sekayasin** [comment]
Yap, im pushing bit per bit.. thanks @SokoPaulSokool

**Pull request merged**
