### PR TITLE
Add admin login page, admin dashboard, Modified Readme 160380295

### PR DESCRIPTION
**Pull request by sekayasin**
## 3Fs Admin Login page, Admin Dashboard
This commit delivers a admin login and a admin dashboard for the 3Fs web portal\
Checkout the Demo 3Fs website [here](http://sekayasin.github.io/3Fs/UI)
Checkout the Admin Demo Login and Admin Dashboard [here](http://sekayasin.github.io/3Fs/UI/admin.html)

### Slow internet connection, page loading my delay, this is why..
- Lato Google Font has been used for typograpghy.
- Images and backgrounds images are embedded from unsplash. website first fetchs them..

### NOTE
- Website is not Mobile First! Kindly don't test on your mobile Devices
- Website has a max width of 1140px!

@SokoPaulSokool @NtaleShadik some reviews! thanks

### CODE REVIEW

**Comment by SokoPaulSokool** [comment]
Wow, nice work. Great job

**Comment by ekumamait** [comment]
The site is beautiful just implement responsiveness and you’re good 👏🏿

**Comment by sekayasin** [comment]
thanks @SokoPaulSokool @ekumamait Yes @ekumamait modern web as a MUST , must be responsive! @media queries are in the kitchenSink! tho at a moment i have pulled the plug out and paused lil bit on pushing commits on it as i feel like i need to work on Challenge2  .., bootcamp so speedY like Boltman! i think i will need a lil yacht to run to bahamas for a Vacation..

**Comment by Luleherll** [comment]
your site is really good. just responsiveness and you take the trophy

**Pull request merged**
