### PR TITLE
Ft user signin up dashboard 160377956

### PR DESCRIPTION
**Pull request by sekayasin**
## 3Fs User Sign-in, Sign Up and User Dashbaord
This commit delivers a user sign-in, sign-up and dashboard pages for the 3Fs web portal
Check out the add pages [here](https://sekayasin.github.io/3Fs/UI)

### Slow internet connection, page loading my delay, this is why..
- Lato Google Font has been used for typograpghy.
- Images and backgrounds images are embedded from unsplash. website first fetchs them..

### CODE REVIEW

**Comment by SokoPaulSokool** [comment]
Good work. nice interface

**Comment by kdaglas** [comment]
its good you gave the reason for the slowness. so ive no reason to complain... thought i would advise, for user-friendly experience, let it not be slow... download your images and your fonts and let them be fetched locally...

**Comment by sekayasin** [comment]
@kdaglas @SokoPaulSokool thanks guys! @kdaglas Ya, very true! but the modern internet in 2018 should be speedy enough to pace with tech demands! many cdns, APIs services everywhere, and plus more caching implementations  by local telecos in pipelines!  no need to worry about slow internet connections..

**Review by Nta1e — APPROVED** [review]
good work..the kind that makes me feel like i've done nothing

**Comment by sekayasin** [comment]
@NtaleShadik , No worries bro! u've done great, actually checked on yo work, it was awesome! with killer frontend UI design.., the css kung-fu comes with time.., and hopefully one day u hang in there..

**Comment by jeanjoe** [comment]
@sekayasin  this is a very good work, Kudos!

**Comment by MuhweziDeo** [comment]
This very good too good if I did half of that would be an achievement

**Comment by kdaglas** [comment]
This is a really amazing and dope landing page... like for a pro front-end coder

**Pull request merged**
